### ISSUE TITLE
Context not emptied on change

### ISSUE THREAD

**Issue by MXClyde** [mendix/FormatString#19]
In https://github.com/mendix/FormatString/blob/master/src/formatstring/widget/formatstring.js#L90 values should be emptied before ending the function.

**Comment by JelteMX** [comment]
Adding a [``hidden``](https://github.com/mendix/FormatString/blob/master/src/formatstring/widget/formatstring.js#L90) class should do the trick

**Comment by JelteMX** [comment]
Fixed in [5.5.2](https://github.com/mendix/FormatString/releases/tag/v5.5.2)
