### ISSUE TITLE
What is the use of Translatable string boolean

### ISSUE THREAD

**Issue by RCatersels** [mendix/FormatString#22]
Hello Jelte,

I have a couple of question about this widget. When the translatable string is set to No I would have expected that it would show the same string in the other languages. This is not the case. When I switch language the string is not shown at all. So this boolean does not seem to work. Furthermore is this functionality nowhere in the documentation. Very funy when you test the widget as an English user while you set a Dutch string. Banged my head a couple of times about why the string was not showing :confounded:

In the documentation I have the option "Display as" but that option is not to be found in the properties.
Same about these properties that are in the documentation but not in the properties of the widget.
Datetime format - Renders datetime attribute as date and/or time. Relative will render the date relative to current datetime.
Date pattern - Overrides the date part with the dojo/data/locale pattern specified. (e.g MMMM d, 'in the year' yyyy GGGG)
Time pattern - Overrides the time part with the dojo/data/locale pattern specified. (e.g h:m:s.SSS a z)
Decimal Precision - The number of decimals to display.
Group Digits - Displays separator character in case of a number datatype

So how do I style the date and numbers?

Or am I missing something here?
Have a nice weekend and regards,

Ronald

**Comment by JelteMX** [comment]
@RCatersels I have made some improvements for the widget and added to [5.6.0](https://github.com/mendix/FormatString/releases/tag/v5.6.0)

- There was an issue where, if the locale of your app would not be `nl-nl` or `en-us`, and you were not using translatable strings, it wouldn't show anything. Thanks for pointing to that issue. You can now set this is the widget. If you choose `automatic`, it will try to determine by itself, and if it can't find the translation, it does a fallback to `en-us`
- I added the missing properties to the README, hopefully it makes sense
- Styling your date and numbers can be possible by doing something in the widget as `<span class="dateTime">${dateTimeVariable} </span>` and add the class `.dateTime` to your project styling. Hope that makes sense?

**Comment by RCatersels** [comment]
Thank you. I will test again. And if I still have questions I will ask.
