### ISSUE TITLE
Text in FormatString not refreshed in DataView

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/FormatString#3]
Text in FormatString not refreshed in DataView. 

1. Run Testproject
2. Click "Add years & Refresh in client" 

Result: Age not updated. After a refresh of the page, age is updated.

**Comment by mgroeneweg** [comment]
I ran into the same issue. Also happens with the 5.14 version

**Comment by MxPvdK** [comment]
Fixed in latest release
