### ISSUE TITLE
Formatstring not working properly in Mendix 8 

### ISSUE THREAD

**Issue by JelteMX** [mendix/FormatString#33]
Customer had an error in their project, which was related to Formatstring. This is in Mendix 8, where the widget breaks on the following line:

[formatstring.js#L135](https://github.com/mendix/FormatString/blob/master/src/formatstring/widget/formatstring.js#L135)

`MxObject.isCurrency` was deprecated in Mendix 6 and finally removed in Mendix 8, per [this release note](https://docs.mendix.com/releasenotes/studio-pro/8.0#float-currency) which means it doesn't exist anymore. We should probably remove the isCurrency check, or make sure it is properly checked in the if-statement

**Comment by Andries-Smit** [comment]
Hi Jelte,

Did the customer moved to latest version 6.0.0 of the format string?

The line https://github.com/mendix/FormatString/blob/master/src/formatstring/widget/formatstring.js#L135 has the proper condition checked. 

https://github.com/mendix/FormatString/releases even mention 8 compatibility 

Cheers, Andries
