### ISSUE TITLE
Multi language?

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/FormatString#4]
I modified the widget by myself to support the dutch language. Is it possible to configurate this? how to solve this issues within widgets? systemtexts?

**Comment by RoelandSalij** [comment]
To say something sensible about configuring dutch language support, we have to know in what way you modified the widget. Can you elaborate on that?

The display string property is of type translatable string and therefore is multi language. 

Which issues are you referring to?

**Comment by pimvdnoll** [comment]
_parseTimeAgo: function (value) {
			var date = new Date(value),
				now = new Date(),
				appendStr = (date > now) ? 'vanaf nu' : 'geleden',
				diff = Math.abs(now.getTime() - date.getTime()),
				seconds = Math.floor(diff / 1000),
				minutes = Math.floor(seconds / 60),
				hours = Math.floor(minutes / 60),
				days = Math.floor(hours / 24),
				weeks = Math.floor(days / 7),
				months = Math.floor(days / 31),
				years = Math.floor(months / 12);

			function createTimeAgoString(nr, unitSingular, unitPlural) {
				return nr + " " + (nr === 1 ? unitSingular : unitPlural) + " " + appendStr;
			}

			 if (seconds < 60) {
            return createTimeAgoString(seconds, "seconde", "seconden");
			} else if (minutes < 60) {
				return createTimeAgoString(minutes, "minuut", "minuten");
			} else if (hours < 24) {
				return createTimeAgoString(hours, "uur", "uur");
			} else if (days < 7) {
				return createTimeAgoString(days, "dag", "dagen");
			} else if (weeks < 5) {
				return createTimeAgoString(weeks, "week", "weken");
			} else if (months < 12) {
				return createTimeAgoString(months, "maand", "maanden");
			} else if (years < 10) {
				return createTimeAgoString(years, "jaar", "jaren");
			} else {
				return "lang geleden "+appendStr;
			}
		},

**Comment by RoelandSalij** [comment]
We will research if we can create a generic solution for this issue.

**Comment by RCatersels** [comment]
+1 Just found out that it shows the english terms when using the relative option in the date format.

**Comment by pimvdnoll** [comment]
workaround for you is to c/p the code above Ronald ;-)

**Comment by ChrisdeG** [comment]
Can you add the terms in the property list as translatable strings? Would solve this issue
