### ISSUE TITLE
Optional microflow causes errors in log

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/FormatString#9]
Indeed the onclick microflow. It occurs when the formatstring is used in a listview with a onclick MF on this Listview. I stripped the onclick MF out of the widget (because not used). But it should be better fixed in the widget itself. I'll post it also on gitub

see https://mxforum.mendix.com/questions/7937/Invalid-JSONRequest-JSONObjectactionname-not-found

**Comment by RoelandSalij** [comment]
Hi Pim, 
I was not able to reproduce this behaviour. Also the following lines should prevent adding the click event to the widget in case there is no onclick microflow configured:
```javascript
if (this._shouldRenderHtml() && this.onclickmf !== '') {
                this.connect(this._wgtNode, "onclick", this.execmf);
}
```

Can you please fork this repository and extend the test project with a reproducible test case?

Thanks!

**Comment by pimvdnoll** [comment]
I got a situation to reproduce:
- Template grid with an default edit button
- In a template item the format string

onclick it will fire the error message. The fix above won't work.
![2015-04-24 10_17_01-tomedia main line - mendix business modeler 5 13 1 - e__documents_tomedia-main](https://cloud.githubusercontent.com/assets/8796208/7315169/12ac021c-ea6b-11e4-9cb5-b6dcbbbb54dd.png)
